events {}

http {
  upstream registry_backend {
    server registry:5000;
  }

  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /certs/nginx.crt;
    ssl_certificate_key /certs/nginx.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    proxy_buffering           off;
    client_max_body_size      0;
    chunked_transfer_encoding on;

    location /v2/ {
      auth_basic           "Docker Registry";
      auth_basic_user_file /etc/nginx/htpasswd;

      set $block 0;
      if ($remote_user = "reader") {
        set $block 1;
      }
      if ($request_method !~ ^(GET|HEAD)$) {
        set $block "${block}1";
      }
      if ($block = "11") {
        return 403 "Push not allowed for reader\n";
      }

      proxy_pass                         https://registry_backend;
      proxy_ssl_verify                   off;
      proxy_set_header Host              $http_host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
